# Generated by Django 5.2.7 on 2025-11-05 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0004_alter_checkin_aadhaar_card_alter_checkin_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_service', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inroom_facilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscellaneous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='guests.checkin')),
                ('check_out', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='guests.checkout')),
            ],
        ),
    ]
