# Generated by Django 5.2.7 on 2025-11-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='inroom_facilities',
            new_name='in_room_facilities',
        ),
    ]
