# Generated by Django 5.2.7 on 2025-11-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_inroom_facilities_billing_in_room_facilities'),
        ('guests', '0004_alter_checkin_aadhaar_card_alter_checkin_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='check_out',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='guests.checkout'),
        ),
    ]
