# Generated by Django 5.2.7 on 2025-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billing_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='room_bill',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
