# Generated by Django 5.2.7 on 2025-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billing_room_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bottles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='food',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='in_room_facilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='miscellaneous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='room_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
