# Generated by Django 5.2.7 on 2025-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billing_bottles_alter_billing_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bottles',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='food',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='in_room_facilities',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='miscellaneous',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='room_bill',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='room_service',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
