# Generated by Django 5.2.7 on 2025-11-05 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('ER', 'Executive Rooms'), ('DR', 'Deluxe Rooms'), ('NR-(AC)', 'Normal Rooms (AC)'), ('NR-(WAC)', 'Normal Rooms (Without AC)')], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('aadhaar_card', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('alloted_room', models.CharField(max_length=3)),
            ],
        ),
    ]
