# Generated by Django 5.2.7 on 2025-11-05 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_days', models.PositiveIntegerField()),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='guests.checkin')),
            ],
        ),
    ]
