# Generated by Django 5.2.7 on 2025-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='no_of_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
