# Generated by Django 5.2.7 on 2025-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_checkout_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='aadhaar_card',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='no_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
