# Generated by Django 5.2.7 on 2025-11-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_checkin_aadhaar_card_alter_checkin_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total_bill',
        ),
    ]
