# Generated by Django 5.2.7 on 2025-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_remove_checkout_total_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='no_of_days',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
